pipeline {

    agent any

    environment {
        DOCKER_USERNAME = "your-dockerhub-username"
        IMAGE_TAG = "v${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('application/microservices-demo/src/frontend') {
		   sh 'docker build -t sandeep2514/frontend:${IMAGE_TAG} .'
		   sh "docker tag sandeep2514/frontend:${IMAGE_TAG} sandeep2514/frontend:latest"
		}
            }
        }
	
	stage('Docker Login') {
    		steps {
        	   withCredentials([usernamePassword(
            		credentialsId: 'dockerhub',
            		usernameVariable: 'DOCKER_USER',
           	 	passwordVariable: 'DOCKER_PASS'
        		)]) {
            		sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
        		}
    		    }
		}

	stage('Push Docker Image') {
 		   steps {
        		sh "docker push sandeep2514/frontend:${IMAGE_TAG}"
       		 	sh "docker push sandeep2514/frontend:latest"
   		    }
		}

        stage('SonarQube Analysis') {
            steps {
                echo 'Running SonarQube Analysis...'
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Building Docker Images...'
            }
        }

        stage('Docker Push') {
            steps {
                echo 'Pushing Docker Images to Docker Hub...'
            }
        }

    }

    post {

        always {
            echo 'Pipeline execution completed.'
        }

        success {
            echo 'Build completed successfully.'
        }

        failure {
            echo 'Build failed.'
        }

    }

}
